variables:
  lldbBuildId: 221

  setenvLinux: |
      export PATH=$HOME/.cargo/bin:$PATH
  setenvOSX: |
      export PATH=$HOME/.cargo/bin:$PATH
  setenvWindows: |
      set PATH=%USERPROFILE%\.cargo\bin;%PATH%
      set PYTHONHOME=%USEPYTHONVERSION_PYTHONLOCATION%
      set PYTHONPATH=%PYTHONHOME%\Lib;%PYTHONHOME%\DLLs

##########################################

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project: 'llvm-build'
      pipeline: 'vadimcn.llvm-build'
      buildVersionToDownload: specific
      buildId: $(lldbBuildId)
      downloadType: single
      artifactName: 'lldb'
      itemPattern: 'lldb/lldb-linux.zip'
    displayName: 'Download LLDB'

  - script: |
      unzip $(System.ArtifactsDirectory)/lldb/lldb-linux.zip -d $(System.ArtifactsDirectory)/lldb-linux
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-x86_64-unknown-linux-gnu
      echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
      npm install
    displayName: 'Install'

  - script: |
      $(setenvLinux)
      mkdir build
      cd build
      cmake -DLLDB_ROOT=$(System.ArtifactsDirectory)/lldb-linux ..
    displayName: 'Configure'

  - script: |
      $(setenvLinux)
      cmake --build build
    displayName: 'Build'

  - script: |
      $(setenvLinux)
      export ADAPTER_LOG=/tmp/adapter.test.log
      cmake --build build --target test_adapter
    displayName: 'Test1'
    condition: always()

  - script: |
      $(setenvLinux)
      export ADAPTER_LOG=/tmp/adapter2.test.log
      cmake --build build --target test_adapter
    displayName: 'Test2'
    condition: always()

  - script: |
      cat /tmp/adapter.test.log
      echo ------------------------
      cat /tmp/adapter2.test.log
      echo - env ------------------
      env
      echo - dir -----------------------
      ls -R $(System.ArtifactsDirectory)
    displayName: 'On Failure'
    condition: failed()

##########################################

- job: OSX
  pool:
    vmImage: 'macOS 10.13'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project: 'llvm-build'
      pipeline: 'vadimcn.llvm-build'
      buildVersionToDownload: specific
      buildId: $(lldbBuildId)
      downloadType: single
      artifactName: 'lldb'
      itemPattern: 'lldb/lldb-osx.zip'
    displayName: 'Download LLDB'

  - script: |
      unzip $(System.ArtifactsDirectory)/lldb/lldb-osx.zip -d $(System.ArtifactsDirectory)/lldb-osx
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-x86_64-apple-darwin
      npm install
    displayName: 'Install'

  - script: |
      $(setenvOSX)
      mkdir build
      cd build
      cmake -DLLDB_ROOT=$(System.ArtifactsDirectory)/lldb-osx ..
    displayName: 'Configure'

  - script: |
      $(setenvOSX)
      cmake --build build
    displayName: 'Build'

  - script: |
      $(setenvOSX)
      export ADAPTER_LOG=/tmp/adapter.test.log
      cmake --build build --target test_adapter
    displayName: 'Test1'
    condition: always()

  - script: |
      $(setenvOSX)
      export ADAPTER_LOG=/tmp/adapter2.test.log
      cmake --build build --target test_adapter2
    displayName: 'Test2'
    condition: always()

  - script: |
      cat /tmp/adapter.test.log
      echo ------------------------
      cat /tmp/adapter2.test.log
      echo - env ------------------
      env
      echo - dir -----------------------
      ls -R $(System.ArtifactsDirectory)
    displayName: 'On Failure'
    condition: failed()

 ##########################################

- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - script: |
      where make
      where gmake
      make -version
    displayName: 'Info'

  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: specific
      project: 'llvm-build'
      pipeline: 'vadimcn.llvm-build'
      buildVersionToDownload: specific
      buildId: $(lldbBuildId)
      downloadType: single
      artifactName: 'lldb'
      itemPattern: 'lldb/lldb-windows.zip'
    displayName: 'Download LLDB'

  - script: |
      unzip $(System.ArtifactsDirectory)/lldb/lldb-windows.zip -d $(System.ArtifactsDirectory)/lldb-windows
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-x86_64-pc-windows-msvc
      set PATH=%USERPROFILE%\.cargo\bin;%PATH%
      rustup toolchain add nightly-x86_64-pc-windows-gnu
      call npm install
    displayName: 'Install'

  - task: BatchScript@1
    inputs:
      filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
      arguments: -arch=amd64 -host_arch=amd64
      modifyEnvironment: true
    displayName: VsDevCmd

  - script: |
      $(setenvWindows)
      mkdir build
      cd build
      cmake -G"Unix Makefiles"^
            -DLLDB_ROOT=$(System.ArtifactsDirectory)\lldb-windows^
            -DCMAKE_C_COMPILER=cl^
            -DCMAKE_CXX_COMPILER=cl^
            ..
    displayName: 'Configure'

  - script: |
      $(setenvWindows)
      cmake --build build
    displayName: 'Build'

  - script: |
      $(setenvWindows)
      set ADAPTER_LOG=%TEMP%\adapter.test.log
      cmake --build build --target test_adapter_gnu
    displayName: 'Test1 GNU'
    condition: always()

  - script: |
      $(setenvWindows)
      set ADAPTER_LOG=%TEMP%\adapter2.test.log
      cmake --build build --target test_adapter2_gnu
    displayName: 'Test2 GNU'
    condition: always()

  - script: |
      $(setenvWindows)
      set ADAPTER_LOG=%TEMP%\adapter.test.log
      cmake --build build --target test_adapter_msvc
    displayName: 'Test1 MSVC'
    condition: always()

  - script: |
      $(setenvWindows)
      set ADAPTER_LOG=%TEMP%\adapter2.test.log
      cmake --build build --target test_adapter2_msvc
    displayName: 'Test2 MSVC'
    condition: always()

  - script: |
      type %TEMP%\adapter.test.log
      echo ------------------------
      type %TEMP%\adapter2.test.log
      echo - env ------------------
      env
      echo - dir -----------------------
      ls -R $(System.ArtifactsDirectory)
      echo - dir -----------------------
      ls -R
    displayName: 'On Failure'
    condition: failed()
